default:
  image: "zelec/manjarolinux:latest"

stages:         
  - deploy

build:       
  stage: build
  script:


deploy:      
  stage: deploy  
  before_script:
    - pacman -Syu --needed --noconfirm vagrant
  script:
    - vagrant cloud auth login --token "${VAGRANT_API_TOKEN}"
    - vagrant cloud auth login --check
