default:
  image: "zelec/manjarolinux:latest"

stages:         
  - build
  - deploy

build:       
  stage: build
  script:
    - pacman -Syu --noconfirm packer
    - (cd mai-base && PACKER_LOG=1 packer build manjaro-arm-installer.pkr.hcl)


deploy:      
  stage: deploy  
  before_script:
    - pacman -Syu --needed --noconfirm vagrant
  script:
    - vagrant cloud auth login --token "${VAGRANT_API_TOKEN}"
    - vagrant cloud auth login --check
