name: Vagrant cloud release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: apt install vagrant

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Vagrant
      run: |
        vagrant cloud auth login --help


