name: Vagrant cloud release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get -y install qemu
          sudo apt-get -y install packer
      - name: Run packer
        run: (cd mai-base && PACKER_LOG=1 packer build manjaro-arm-installer.pkr.hcl)
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Install Vagrant
        run: |    
          sudo apt-get update
          sudo apt-get -y install vagrant
      - name: Connect to Vagrant
        run: |
          vagrant cloud auth login --token ${{ secrets.MAI_TOKEN }}
          vagrant cloud auth login --check
          ls mai-base
